### ISSUE TITLE
Bug in the authenticate method of the AuthenticationService class

### ISSUE THREAD

**Issue by santclear** [RedFroggy/angular-spring-hmac#10]
Hello Michael. Thanks for sharing, this project helped me a lot.
I'm studying Spring Security with your project. I tried to change the username, then log in with that changed name. The application returns Access Denied.
As a self challenge, I tried to fix it. I do not know if it is the right solution. Please, see below.
In the authenticate method of the AuthenticationService class I override the lines 55 through 57 by  `tokenAuthentication(loginDTO.getLogin(), loginDTO.getPassword());`
The called method is

```
public void tokenAuthentication(String username, String password){
        UserDetails details = userDetailsService.loadUserByUsername(username);
        UsernamePasswordAuthenticationToken authToken = new UsernamePasswordAuthenticationToken(details, password, details.getAuthorities());
        if(password.equals(details.getPassword())) {
	        SecurityContextHolder.getContext().setAuthentication(authToken);
        } else {
        	authenticationManager.authenticate(authToken);
        }
    }
```

I would like your opinion if this is an appropriate solution. Thanks in advance.

**Comment by michaeldesigaud** [comment]
Hello, i've plugged the application to an H2 in memory database in which i store the users. Can you test and tell me if it fix your problem ?
