### ISSUE TITLE
Not able to read custom headers

### ISSUE THREAD

**Issue by javatechy** [RedFroggy/angular-spring-hmac#12]
I used the angular2 branch  from this project and splitted it  into angular project and spring boot project. Same code which works with in repo doesn't work  after splitting the project. Angular code is not able to read any tokens.

I am using angular 4.0.2

    ```
"@angular/animations": "^4.0.2",
    "@angular/common": "^4.0.2",
    "@angular/compiler": "^4.0.2",
    "@angular/core": "^4.0.2",
    "@angular/forms": "^4.0.2",
    "@angular/http": "^4.0.2",
    "@angular/platform-browser": "^4.0.2",
    "@angular/platform-browser-dynamic": "^4.0.2",
    "@angular/platform-server": "^4.0.2",
    "@angular/router": "^4.0.2",
    "@angular/upgrade": "^4.0.2",
    "angular-utf8-base64": "0.0.5",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "crypto-js": "^3.1.9-1",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "ntypescript": "^1.201609302242.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.1.0",
    "systemjs": "^0.20.12",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.4"

```

**Comment by michaeldesigaud** [comment]
I haven't upgraded the project to Angular 4.0.2 so i haven't tested yet. Can you be more specific ? do you have any errors or stack trace in the front or the back ?

**Comment by michaeldesigaud** [comment]
Hi, i've updated angular to version 4. Can you test again and tell me if your problem is still here ?
