### ISSUE TITLE
issues angular2

### ISSUE THREAD

**Issue by widedbenabd** [RedFroggy/angular-spring-hmac#13]
First of all i want to thank you for this great tuto. 
However when i started including this code into my project (front end: angular2, back-end: spring-boot, spring-mvc, spring-data, hibernate) i've recieved some issues like: 

* ReferenceError: _ is not defined. 
* and Cannot find name 'CryptoJS'.

Also i want to know how to redirect each user to the specified layout using this code

**Comment by michaeldesigaud** [comment]
Hi, i've updated angular to version 4. Can you test again and tell me if your problem is still here ?
