### ISSUE TITLE
Handling File uploads

### ISSUE THREAD

**Issue by thomas-mwania** [RedFroggy/angular-spring-hmac#14]
This is such a great tutorial and an incredibly good place to start. When i was implementing this code on my project, i realized the the Digest Auth will always fail for file uploads. This is basically because of the method for calculating the server digest does not take into account files(wrappedRequest.getBody).

I would appreciate your contribution on this.

**Comment by michaeldesigaud** [comment]
The request.getBody() is taking in account as you can see here:

https://github.com/RedFroggy/angular-spring-hmac/blob/master/src/main/java/fr/redfroggy/hmac/service/SecurityService.java#L110
