### ISSUE TITLE
Problems when migrating to angular2 rc.1

### ISSUE THREAD

**Issue by RELATO** [RedFroggy/angular-spring-hmac#5]
Hi

Could you please help migrating your project to angular 2 rc.1 ? 

I must to say that I loved your security angular2 and springboot aproach and I am going to use it. 

At the moment I am testing your another project called "angular 2 dynamic form"  

Congratulations,

**Comment by michaeldesigaud** [comment]
Thanks for your feedback! 
I've just updated the angular2 branch and it's now up to date with rc.1 version. I'll do the same for the "angular 2 dynamic form" project
