### ISSUE TITLE
secret null / hmac message null

### ISSUE THREAD

**Issue by celghandour** [RedFroggy/angular-spring-hmac#6]
Bonjour  , 

en essayant d’intégrer le projet dans un Spring MVC  j'ai ça cote client  :

secret null    hmac-http-client.ts:45 
hmac message null

et j'ai pas de sysout cote serveur  sur la classe HmacSecurityFilter  .

Merci d'avance .

**Comment by michaeldesigaud** [comment]
This should be fixed
